# Generated by Django 4.2.6 on 2023-12-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_coursewatch_user'),
        ('users', '0024_remove_coursewatch_user'),
    ]

    operations = [
    ]
